### ISSUE TITLE
Local installation question

### ISSUE THREAD

**Issue by Paul-dH** [11ty/eleventy#249]
Hi All,

I've copied my local development git folder and wanted to launch eleventy on my local system.

Do do this I've run the following commands:
```
$ sudo apt install npm
$ npm install --save-dev @11ty/eleventy
$ sudo npm i -g npx
$ npx eleventy
```

I did get some warnings after the `npm install --save-dev @11ty/eleventy` command:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /glob-watcher/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /nunjucks/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
```

But when I run `npx eleventy` I get the error below, how can I fix this? I did found the filter in eleventy.js though.

```
Problem writing eleventy templates (more info in DEBUG output): 
 * Error: Having trouble rendering template ./tags.njk: 
<h1>Tagged “{{ tag }}”</h1>

{% set postslist = collections[ tag ] %}
{% include "components/postslist.njk" %}

<nav>
  <a href="{{ '/blog/' | url }}">← Blog index</a>
</nav>

 * Template render error: (unknown path)
  Template render error: (/home/paul/Projects/scripters.blog-dev/_includes/components/postslist.njk)
  Error: filter not found: machineDate
```

Any idea how I can fix this, I really like to start developing locally, maybe I missed something?

Thanks! Paul

**Comment by zachleat** [comment]
Hey Paul! I think those warnings are probably fine. If anything they would cause problems for --watch and not the regular build.

Can you add your postslists file content? I don't recognize that machineDate filter. Did you add that?

**Comment by Paul-dH** [comment]
Hi Zachleat!

Thank you for your super fast reaction :)

Btw, I used the [Eleventy Netlify Boilerplate](https://github.com/danurbanowicz/eleventy-netlify-boilerplate) as a starting point.

The content of _includes/components/postslist.njk:
```
<section>
	{% for post in postslist | reverse %}
		<article{% if post.url == url %} data-current="current item"{% endif %}>
			<h3>
				<a href="{{ post.url | url }}">
					{% if post.data.title %}
						{{ post.data.title }}
					{% else %}
						Untitled
					{% endif %}
				</a>
			</h3>
			{% if post.data.summary %}
				<p>
					{{ post.data.summary }}
				</p>
			{% endif %}
			<p>
				<time datetime="{{ post.date | machineDate }}">
					<small>{{ post.date | readableDate }} by {{ metadata.author.name }}</small>
				</time>
			</p>
			{% if post.data.tags %}
				<p>
					{% for tag in post.data.tags %}
		  			{%- if tag != "post" -%}
		  				{% set tagUrl %}/tags/{{ tag }}/{% endset %}
		  			<a href="{{ tagUrl | url }}" rel="tag">{{ tag }}</a>
		  			{%- endif -%}
					{% endfor %}
				</p>
			{% endif %}
		</article>
	{% endfor %}
</section>
```

The filter definition in eleventy.js:
```
  eleventyConfig.addFilter("machineDate", dateObj => {
    return DateTime.fromJSDate(dateObj).toFormat("yyyy-MM-dd");
  });
```

I did get some progress now, I wanted to search a litle deeper and tryed the debug option. In the debug log there were errors of all 3 dependencies missing listed in the package.json:
```
    "clean-css": "^4.1.11",
    "html-minifier": "^3.5.19",
    "uglify-js": "^3.4.5"
```

I did had to do a global install to use the debug option, but after fixing those dependencies eleventy --serve works now:
```
sudo npm i clean-css
sudo npm i html-minifier
sudo npm i uglify-js
```
Should the dependencies be installed together with eleventy, or did I had to install them manually after the eleventy install? I'm a bit new here, so I don't know.

**Comment by zachleat** [comment]
Hmm, so yeah it looks like the steps you wanted (and finally got to) were:

1. Check out (Make a local copy) of the `eleventy-netlify-boilerplate`
2. Run `npm install` in that directory to get a local copy of eleventy and all project dependencies
3. Build using `npx eleventy`

**Comment by zachleat** [comment]
I’ve been working on the error messaging for 0.5.4 so hopefully it’ll be a little bit easier to understand in the future.

**Comment by Paul-dH** [comment]
> I’ve been working on the error messaging for 0.5.4 so hopefully it’ll be a little bit easier to understand in the future. You can read more about that work here: #182

This looks good, the returned error now gives a hint where a issue should be fixed. Nice work!

And the steps you wrote above are indeed somewhat the same as what I did to fix it. I now have a globally installed version of Eleventy.

Maybe a dumb question, but is it also now possible to update eleventy with the Ubuntu updates using this global install? Like: `apt-get update && apt-get upgrade`?

We're now off building my cool project, looking forward to it :)

**Comment by zachleat** [comment]
I usually recommend that people use a local copy of Eleventy, a la https://www.11ty.io/docs/local-installation/

This will cause you fewer headaches long term. The version will then be controlled in your project’s `package.json`.

If you want to update a package, here are the npm docs for that: https://docs.npmjs.com/cli/update

Generally you’ll use `npm update @11ty/eleventy` in the project folder to upgrade just eleventy.

**Comment by zachleat** [comment]
One more thing: `npm update @11ty/eleventy -g` should upgrade your global version.

**Comment by Paul-dH** [comment]
Ah ok sweet, thanks again for the info!

**Comment by MrKrautee** [comment]
the error still exists. current version, no changes: 
`kraut@krauts-top> npx eleventy
Problem writing Eleventy templates: (more in DEBUG output)
> Having trouble rendering njk template ./tags.njk

`TemplateContentRenderError` was thrown
> (./tags.njk)
  Template render error: (/home/kraut/projects/probaum/cms/_includes/components/postslist.njk)
  Error: filter not found: machineDate

`Template render error` was thrown:
    Template render error: (./tags.njk)
      Template render error: (/home/kraut/projects/probaum/cms/_includes/components/postslist.njk)
      Error: filter not found: machineDate
        at Object._prettifyError (/home/kraut/projects/probaum/cms/node_modules/nunjucks/src/lib.js:36:11)
        at /home/kraut/projects/probaum/cms/node_modules/nunjucks/src/environment.js:561:19
        at eval (eval at _compile (/home/kraut/projects/probaum/cms/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:32:11)
        at /home/kraut/projects/probaum/cms/node_modules/nunjucks/src/environment.js:569:11
        at Template.root [as rootRenderFunc] (eval at _compile (/home/kraut/projects/probaum/cms/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:119:3)
        at Template.render (/home/kraut/projects/probaum/cms/node_modules/nunjucks/src/environment.js:550:10)
        at eval (eval at _compile (/home/kraut/projects/probaum/cms/node_modules/nunjucks/src/environment.js:631:18), <anonymous>:31:10)
        at fn (/home/kraut/projects/probaum/cms/node_modules/a-sync-waterfall/index.js:26:24)
        at /home/kraut/projects/probaum/cms/node_modules/a-sync-waterfall/index.js:66:22
        at executeSync (/home/kraut/projects/probaum/cms/node_modules/a-sync-waterfall/index.js:8:15)
Wrote 0 files in 0.21 seconds (v0.11.1)
`

**Comment by pdehaan** [comment]
@MrKrautee From the looks of your error message, it's complaining that it doesn't understand what the custom "machineDate" filter is:

> Error: filter not found: machineDate

Not sure that's related to a local vs npx installed version of eleventy. But if you have a public repo somewhere, I can take a look and we can try debugging.

**Comment by MrKrautee** [comment]
sorry my fault! using eleventy-netlify-boilerplate, some files were missing, like .eleventy.js. completely my fault, sorry! :D
