### ISSUE TITLE
`addPreprocessor` doesn't work together with keyed `addExtension` 

### ISSUE THREAD

**Issue by mayank99** [11ty/eleventy#3433]
### Operating system

macOS 14

### Eleventy

3.0.0-alpha.19

### Describe the bug

I'm trying to use `addPreprocessor` to transform the input file contents before handing it off to a template renderer.

This works for simple cases, but I've hit a wall when trying to use it with `key`ed `addExtension` (for [aliasing an existing template language](https://www.11ty.dev/docs/languages/custom/#aliasing-an-existing-template-language)). Specifically, I'm trying to use `key: "11ty.js"` so that I can access `this.defaultRenderer` inside the `compile` function. What happens is 11ty tries to process this template too early, before it has been transformed by the logic in `addPreprocessor`, which means it fails when it encounters unsupported syntax.

```
[11ty] Problem writing Eleventy templates:
[11ty] Unexpected token (3:4) (via SyntaxError)
```

### Reproduction steps

See [stackblitz](https://stackblitz.com/edit/github-qaud3e?file=eleventyJsxPlugin.js).

**Note**: I'm only using `"js"` to illustrate the problem more clearly. Using `"jsx"` or `"tsx"` also fails, but with a different "Unknown file extension" error (possibly related to https://github.com/11ty/eleventy/issues/3393#issuecomment-2276921293).

**Note 2**: A similar problem also happens in Deno (which natively supports JSX/TSX), except there is no error; the `content` in `addPreprocessor` is just empty. See [minimal repro](https://github.com/mayank99/11ty-jsx-deno/commit/421c20be51e078a0d8dd3363d3f1cd9f39910c92).

### Expected behavior

`addPreprocessor` should execute _before_ setting up a template alias (i.e. using `addExtension` with `key`). Both features should be usable together. 

### Reproduction URL

https://stackblitz.com/edit/github-qaud3e?file=eleventyJsxPlugin.js

**Comment by zachleat** [comment]
Hmm. Agree that this is a bug. Currently we handle template types that read file content separate from dynamic `import` of JavaScript templates (through the `11ty.js` template type, aliased or not).

The most correct way to fix this is to restructure JavaScript templates to import during the file `read` step, which feels like a refactor that’s a little big for this late in the 3.0 release lifecycle.

This is the place where it forks:
* https://github.com/11ty/eleventy/blob/26c0fcfe7398c98651dfbff485fb7a14173e1aaa/src/TemplateContent.js#L269-L271
* via https://github.com/11ty/eleventy/blob/26c0fcfe7398c98651dfbff485fb7a14173e1aaa/src/Engines/JavaScript.js#L123

I’ve pushed a branch that has the fixes in place but I’m nervous to make this change 😅 https://github.com/11ty/eleventy/compare/issue-3433?expand=1

**Comment by mayank99** [comment]
So I tried the changes from https://github.com/11ty/eleventy/commit/e221e190d5eea74bbb9cbe0bc4c8a882514bb859 locally by editing node_modules, but it still doesn't seem to fix the issue. I get the same SyntaxError in Node, and the `content` is still empty in Deno.

<details><summary>Diff</summary>

```diff
﻿﻿﻿diff --git a/src/Engines/JavaScript.js b/src/Engines/JavaScript.js
index b20db4e0dd43f8305aba431989a4f67d404017cd..568bff12a4c8aac24020f89528d586a6b04165e1 100644
--- a/src/Engines/JavaScript.js
+++ b/src/Engines/JavaScript.js
@@ -123,6 +123,10 @@ class JavaScript extends TemplateEngine {
 		return false;
 	}
 
+	useJavaScriptImport() {
+		return true;
+	}
+
 	async getExtraDataFromFile(inputPath) {
 		let inst = await this.getInstanceFromInputPath(inputPath);
 		return getJavaScriptData(inst, inputPath);
diff --git a/src/Engines/TemplateEngine.js b/src/Engines/TemplateEngine.js
index 05050b68b043a9a7d8383fbb7d3944642f339091..47db94ffb0af10940a1c3a2fe20564e024e443f8 100644
--- a/src/Engines/TemplateEngine.js
+++ b/src/Engines/TemplateEngine.js
@@ -111,6 +111,10 @@ class TemplateEngine {
 		return fn(data);
 	}
 
+	useJavaScriptImport() {
+		return false;
+	}
+
 	// JavaScript files defer to the module loader rather than read the files to strings
 	needsToReadFileContents() {
 		return true;
diff --git a/src/TemplateContent.js b/src/TemplateContent.js
index 143d958282d43348c31b5f0d970f4b03d36d567c..7bae7d7b26b7b6005a95580c606cec0db35bc943 100644
--- a/src/TemplateContent.js
+++ b/src/TemplateContent.js
@@ -184,6 +184,13 @@ class TemplateContent {
 		let content = await this.inputContent;
 
 		if (content || content === "") {
+			if (this.engine.useJavaScriptImport()) {
+				return {
+					data: {},
+					content,
+				};
+			}
+
 			let options = this.config.frontMatterParsingOptions || {};
 			let fm;
 			try {
@@ -266,6 +273,14 @@ class TemplateContent {
 
 	async getInputContent() {
 		let tr = await this.getTemplateRender();
+
+		if (
+			tr.engine.useJavaScriptImport() &&
+			typeof tr.engine.getInstanceFromInputPath === "function"
+		) {
+			return tr.engine.getInstanceFromInputPath(this.inputPath);
+		}
+
 		if (!tr.engine.needsToReadFileContents()) {
 			return "";
 		}

```

</details>

**Comment by zachleat** [comment]
Hmmmmmm—can you supply your test case?

Here’s what I tested with (with the changes) and it had `content` for both the `.11ty.js` and `.test` templates:

https://gist.github.com/zachleat/c54611d86ab2e5c521802b211904eb65

**Comment by zachleat** [comment]
Ah—my apologies for bad reading comprehension! 😭 I’ll have a second look!

**Comment by zachleat** [comment]
I pushed some additional changes to the `issue-3433` which I believe will fix the issue—can you retest? https://github.com/11ty/eleventy/compare/issue-3433?expand=1

**Comment by mayank99** [comment]
Thanks for looking into this again, Zach. I have some good news and more bad news.

I tested out the new changes against both repros ([Node stackblitz](https://stackblitz.com/edit/github-qaud3e?file=eleventyJsxPlugin.js) and [Deno branch](https://github.com/mayank99/11ty-jsx-deno/tree/preprocessor)) and here's what I found:

1. There is no change in Node behavior - it is still throwing a `SyntaxError`.
2. In Deno, the `content` argument of `addPreprocessor` is no longer empty (🎉), *but* it is still not a string. Instead, it is returning an object containing a `render` function (😭), similar to my [previous comment](https://github.com/11ty/eleventy/issues/3433#issuecomment-2356954971). Unless I'm misunderstanding `addPreprocessor`, I don't think this is expected?

**Comment by zachleat** [comment]
Hmm, we’re iterating towards something :D 

Let’s start with the Node behavior first:

I think there is some confusion about the `11ty.js` format—it doesn’t accept strings nor execute string input. Adding a virtual template as an 11ty.js template is just passing in JavaScript. So I wouldn’t expect that the `content` passed to `addPreprocessor` to be a string (nor aliases via `addExtension`).

When you remove `key: '11ty.js'` from your alias, it treats the template as plaintext and then `addPreprocessor` _will_ pass in a string.

Worse, I wouldn’t expect returning a string from `addPreprocessor` to execute a  string of JavaScript either. We have a similar limitation executing arbitrary JS in the Render plugin https://www.11ty.dev/docs/plugins/render/#rendertemplate

I think I would classify that as a bigger enhancement request (not a bug right now).

All that said, we do use the node-retrieve-globals package to implement the `js` front matter type to execute arbitrary JavaScript https://github.com/11ty/eleventy/issues/2819 so there is a limited precedent for a path forward here.

Finally, I would call out the method used by `tsx` https://github.com/privatenumber/tsx (likely some magic using module.register https://nodejs.org/docs/latest/api/module.html#moduleregisterspecifier-parenturl-options but I haven’t dove all the way in to see) that might be a more ergonomic way to intercept and preprocess JavaScript. This is what we recommend on https://www.11ty.dev/docs/languages/typescript/

Open to suggestions here (of course).

**Comment by mayank99** [comment]
Yeah, it sounds like I might have misunderstood what `addPreprocessor` is supposed to do. I was under the impression that I'd be able to do arbitrary transformations to the source code before Eleventy tries to render (or do anything) with it. There was still *a* bug here though, at least in Deno, and it seems to have been fixed by some of the changes you shared above.

I've definitely looked into `tsx` (and `esbuild-register`), however I find these libraries to be too limiting. I want more control over the transformation, which is why I was looking into `addPreprocessor`. That's a good callout on `module.register` though, I'll look into that.

I do wonder if it would be easier to recreate the `11ty.js` renderer (instead of reusing it via `key: "11ty.js"`). Then I could treat it as a fully custom template language which can be preprocessed as a string. Do you have an idea how much work it would be to re-implement `11ty.js`-like compilation on custom templates? Is 11ty doing something more involved or is it just a dynamic import of the actual file on disk? I was thinking I could even use `node-retrieve-globals` as a starting point to extract the `default` export from the stringified code; but then it wouldn't handle things like imports.

Of course, the last resort is to run the pre-transform and 11ty as two separate steps, but I was hoping to avoid producing an intermediate set of files.

**Comment by zachleat** [comment]
I think you can avoid a lot of abstraction complexity tied to `node-retrieve-globals` since you already have `esbuild` in play (specifically the extra restrictions Node.js has placed on `vm` and ESM together) by outputting CJS code from esbuild and using Node’s Module#_compile (dynamic CJS) API directly.

Something like this:

```js
let elev = new Eleventy("./test/stubs-jsx/", undefined, {
  config: eleventyConfig => {
    eleventyConfig.addTemplateFormats('11ty.jsx');

    eleventyConfig.addPreprocessor(
      'jsx-transform',
      ['11ty.jsx'],
      async (data, content) => {
        const { code } = await esbuild.transform(content, {
          loader: 'jsx',
          jsx: 'automatic',
          jsxImportSource: 'preact',
          format: 'cjs',
        });

        let m = new Module();
        let workingDir = pathToFileURL(path.resolve(".")) + "/";
        m.paths = Module._nodeModulePaths(workingDir);
        m._compile(code, workingDir);
        return m.exports;
      }
    );

    eleventyConfig.addExtension(['11ty.jsx'], {
      compile: function (content) {
        return async (data) => {
          // let output = await this.defaultRenderer(data);
          let page = content.default();
          if (isValidElement(page)) {
            return `<!doctype html>${await renderToStringAsync(page)}`;
          }
          return content;
        };
      },
    });
  }
});
```

**Comment by zachleat** [comment]
Regardless, I’ll have a deeper think about the additional changes made in this PR and slate it for 3.0 for now: https://github.com/11ty/eleventy/pull/3452 I do think we made forward progress there—thank you!

**Comment by mayank99** [comment]
Oh wow, TIL about `module._compile`. This looks like an undocumented/private API, which does make me nervous but otherwise it's pretty much exactly what I need. Between this and `module.register`, I think I have a clearer path forward. Thank you!

**Comment by zachleat** [comment]
It _is_ an off-the-books API but _everyone_ uses it. I originally found it via Svelte’s repo I think? Pour one out for https://github.com/nodejs/node/issues/40098

**Comment by zachleat** [comment]
Just published a little research on the different methods that I know of for dynamic script execution in Node.js here: https://github.com/zachleat/node-eval-modules

**Comment by zachleat** [comment]
Shipping with 3.0.0-alpha.21 and 3.0.0-beta.2
