### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by lesichkovm** [11ty/eleventy#689]
**Describe the bug**
Errors during watch

Unhandled rejection in promise: (more in DEBUG output)
Uncaught exception: (more in DEBUG output)
> Cannot read property 'trim' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'trim' of undefined
        at Function.log (/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:41:26)
        at Function.error (/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:32:26)
        at process.on (/node_modules/@11ty/eleventy/cmd.js:24:26)
        at emitTwo (events.js:126:13)
        at process.emit (events.js:214:7)
        at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
        at process._tickCallback (internal/process/next_tick.js:189:7)
Unhandled rejection in promise: (more in DEBUG output)
Uncaught exception: (more in DEBUG output)
> Cannot read property 'trim' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'trim' of undefined
        at Function.log (/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:41:26)
        at Function.error (/node_modules/@11ty/eleventy/src/EleventyErrorHandler.js:32:26)
        at process.on (/node_modules/@11ty/eleventy/cmd.js:24:26)
        at emitTwo (events.js:126:13)
        at process.emit (events.js:214:7)
        at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
        at runMicrotasksCallback (internal/process/next_tick.js:124:9)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickCallback (internal/process/next_tick.js:180:9)

**To Reproduce**
Not sure how to reproduce it just happens

**Expected behavior**
Show correct error is any

**Screenshots**
No screensho

**Environment:**
 - OS and Version: Linux Mint
 - Eleventy Version 0.9.0

**Additional context**
Nothing else

**Comment by paulshryock** [comment]
Can you search your souce code for `trim`, find the file containing the code that is throwing the error, and share the code snippet?

**Comment by zachleat** [comment]
I ran into this locally and fixed it. I believe it was from EleventyErrorHandler receiving the wrong thing from https://github.com/11ty/eleventy/blob/v0.9.0/cmd.js#L23

Nonetheless, it’ll be fixed in 0.9.1.

**Comment by zachleat** [comment]
If you change your local version

https://github.com/11ty/eleventy/blob/v0.9.0/cmd.js#L24

```diff
- EleventyErrorHandler.error(promise, "Unhandled rejection in promise");
+ EleventyErrorHandler.error(error, "Unhandled rejection in promise");
```

it will reveal more

**Comment by lesichkovm** [comment]
I will wait for the next version. Thanks.

**Comment by dbauszus-glx** [comment]
This error seems to still occur. I haven't used eleventy in anger for a month. But now this occurs with node v9.7, 10.16.3, 12.7 and 12.10. I tested against eleventy v0.9 and 0.10.

I try to run following command which worked fine previously.

`npx eleventy --input ./_docs --output ./docs --formats=html,md --pathprefix=/xyz/docs --serve`

**Comment by Ryuno-Ki** [comment]
Confirmed.
As far as I could track it down, it happened during compilation of templates for me.

**Comment by aifeelit** [comment]
@lesichkovm
